### ISSUE TITLE
Good job.

### ISSUE THREAD

**Issue by cellojaan** [ArTTo8/InstagramUnfollowers#1]
Hey. Good works. Can you add please also mutual and ghost followers?

**Comment by alxgord** [comment]
Hi! Can you explain what you mean?

**Comment by cellojaan** [comment]
Hi ArTTo8

Mutual followers is who following user and user following back.

Ghost followers is for example, user do not follow me and I do not follow him but hi like my photo or comment.

Can you do that?

**Comment by cellojaan** [comment]
I have did mutual followers can you do ghost followers @ArTTo8 ?

**Comment by alxgord** [comment]
I will try to implement this in next version.
