### ISSUE TITLE
Application is too Slow

### ISSUE THREAD

**Issue by Aym9n** [ArTTo8/InstagramUnfollowers#4]
i couldn't figure out how to minimize app size even on proguard, also it is too slow how is it possible to make it faster when opening an account and uploading followers.

**Comment by cellojaan** [comment]
So easy to find solution.

**Comment by Aym9n** [comment]
> So easy to find solution.

how is that exactly, app is huge and slow, found nothing to make it faster

**Comment by alxgord** [comment]
> > So easy to find solution.
> 
> how is that exactly, app is huge and slow, found nothing to make it faster

Hi! You can write your own methods to interact with Instagram instead using private API library to reduce apk size.
